### ISSUE TITLE
Consistent Naming

### ISSUE THREAD

**Issue by marc-mabe** [marc-mabe/php-enum#120]
I would like to change the naming in 4.x to be more consistent and also better integrate with the new immutable methods added in 4.x

Current (3.x + 4.x):

| Method                   | Enum | EnumSet | EnumMap | Description |
|--------------------------|------|-------- |---------|-------------|
| has()                    | X(S) | -       | -       | Does enumerator exist |
| contains()               | -    | X       | X       | Does enumerator exist |
| get()                    | X(S) | -       | -       | Get enumerator object |
| attach/detach(Enumerator)| -    | X       | -       | Attach/Detach an enumerator |
| attach/detachEnumerators | -    | X       | -       | Attach/Detach iterable enumerators at once |
| with/withoutEnumerator   | -    | X       | -       | Attach/Detach an enumerator (immutable) |
| with/withoutEnumerators  | -    | X       | -       | Attach/Detach iterable enumerators at once (immutable) |

New:

| Method                   | Enum | EnumSet | EnumMap | Description |
|--------------------------|------|-------- |---------|-------------|
| has()                    | X(S) | X       | X       | Does enumerator exist |
| get()                    | X(S) | -       | X       | Get enumerator object `Enum` / Get mapped data value `EnumMap` |
| add/remove               | -    | X       | X       | Add/Remove an enumerator |
| add/removeIterable       | -    | X       | X       | Add/Remove iterable enumerators at once |
| with/without             | -    | X       | X       | Add/Remove an enumerator (immutable) |
| with/withoutIterable     | -    | X       | X       | Add/Remove iterable enumerators at once (immutable) |

Differences from master (3.x):

* EnumSet::attach   -> EnumSet::add
* EnumSet::detach   -> EnumSet::remove
* EnumSet::contains -> EnumSet::has
* EnumMap::contains -> EnumMap::has

Notes:
* Old methods will be soft deprecated
  * marked as `@deprecated` (no deprecated notice) in 3.x and 4.0
  * trigger deprecation notice in last 4.x
  * removed in 5.x

thoughts @prolic  ?

**Comment by prolic** [comment]
Sure, go ahead.

**Comment by marc-mabe** [comment]
merged by #121
