### ISSUE TITLE
[Bug] getName returns wrong name in edge case

### ISSUE THREAD

**Issue by chescos** [marc-mabe/php-enum#133]
**Detailed description:**

When the value of two enumerators is the same, the `getName` method always returns the name of the first enumerator that has the same value.

**Steps to reproduce:**

1. Create two or more enumerators with the same value, here's an example:

```
use MabeEnum\Enum;

class Test extends Enum
{
    const FIRST_ENUM = [
        'name' => 'Test',
    ];

    const SECOND_ENUM = [
        'name' => 'Test',
    ];

    const THIRD_ENUM = [
        'name' => 'Test',
    ];
}
```

2. Create an instance of `SECOND_ENUM` or `THIRD_ENUM` and call `getName` on it. It will always return `FIRST_ENUM`. Example:

```
$instance = Test::SECOND_ENUM();
$test = $instance->getName();
echo $test; // this echos: FIRST_ENUM
```

**Expected behavior:**

I'd expect the correct name to be returned.

**Environment:**

Important information of your environment.
 - PHP Version: 7.2.5

**Comment by chescos** [comment]
The same issue seems to occur when calling `getOrdinal` on the instance; it'll always be the ordinal of the first enumerator with the same value.

**Comment by chescos** [comment]
@marc-mabe thanks for explaining! Just wondering, is it a PHP spec that enumerator values must be unique or does this only relate to this library?

**Comment by marc-mabe** [comment]
Hi @chescos,

I'm not aware of any enumeration implementation that supports ambiguous constant values. (Like python and Java)

https://en.m.wikipedia.org/wiki/Enumerated_type
> ...  In other words, an enumerated type has values that are different from each other, and that can be compared and assigned ...
