### ISSUE TITLE
`Enum#getValue()` should `@psalm-return static::*`

### ISSUE THREAD

**Issue by Ocramius** [marc-mabe/php-enum#144]
Reporting it mostly for self-reference (want to open a PR when I have time to test it), but the return type of `Enum#getValue()` should be `@psalm-return static::*`, indicating that it is the value of any of the defined constants.

**Comment by marc-mabe** [comment]
I think this would include private, protected and public constants where only public constants are possible.

For PHPStan we have created an extension for this: https://github.com/marc-mabe/php-enum-phpstan
