### ISSUE TITLE
Serializable extended class

### ISSUE THREAD

**Issue by gmusteata** [marc-mabe/php-enum#46]
Hi,

I am trying to find a way to implement serialization, which is needed by my application.
Here is a short example:

    <?php
    namespace Application\Entity\Enum;

    use MabeEnum\Enum;

    /**
     * Class for allowing serialization of enums
     */
    abstract class AbstractEnum extends Enum implements \Serializable
    {

        /**
         * Serialize the value of the Enum object
         *
         * @return string
         */
        public function serialize()
        {
            return serialize($this->getValue());
        }

        /**
         * Unserialize the data in order to re-create the object
         *
         * @param string $data
         */
        public function unserialize($data)
        {
            // Nothing can be done here since Enum does not allow
            // setting the value back
        }
    }

When unserializing, I am not able to set the value back, since there is no setValue method, and the value property is private.

Is there a reason why value cannot be declared at least protected, or create a setValue method?

Thanks

**Comment by marc-mabe** [comment]
The problem is that you have to return the same instance for the same value.
That's the reason why serializing isn't supported.
-> If you find a way to do so feel free to open a PR to implement it on abstract class level.

**Comment by gmusteata** [comment]
I have done some more digging, and it seems that unserialize holds the same instance from serialize.
The PHP manual states that serialize does not call the destructor, and unserialize does not call the constructor. Details here: http://us2.php.net/manual/en/class.serializable.php.

I have used spl_object_hash to compare the ids of the serialized instance and the unserialized instance and they are the same.

**Comment by marc-mabe** [comment]
@gmusteata Please test the following:

```php
$enum = MyEnum::MYCONST();
var_dump($enum === $enum); // -> TRUE
var_dump($enum === unserialze(seralize($enum))); // -> FALSE
```

>  When the data is unserialized the class is known and the appropriate unserialize() method is called as a constructor instead of calling __construct().

It means that PHP will create a *new* instance and calls `unserialize()` instead of `__construct()`.
As of `unseralze()` is an object method it requires an instance to be called on.

So if you don't need one single object you implement it yourself and using reflection to set the private value on parent.
