### ISSUE TITLE
EnumSerializableTrait

### ISSUE THREAD

**Issue by marc-mabe** [marc-mabe/php-enum#52]
Implementing a trait than can simply be used to make an enumeration serializable.

As long as it's impossible in PHP to make a singleton serializable this functionality should be used carefully and needs to be implemented itself. This trait will help to activate it if really required.

Usage example:
```php
use MabeEnum\Enum;
use MabeEnum\EnumSerializableTrait;
use Serializable;

class CardinalDirection extends Enum implements Serializable
{
    use EnumSerializableTrait;

    const NORTH = 'n';
    const EAST = 'e';
    const WEST = 'w';
    const SOUTH = 's';
}

$north1 = CardinalDirection::NORTH();
$north2 = unserialize(serialize($north1));
var_dump($north1 === $north2); // FALSE <- this is the wrong behavior you could run into
```

**Comment by marc-mabe** [comment]
see #43 & #46

**Comment by Michal-sk** [comment]
Do you have any suggestion on using this with __clone __sleep and __wakeup. Because Enum makes those functions final and throws a LogicException.

**Comment by marc-mabe** [comment]
@Michal-sk Why do you want to use it based on `__sleep` / `__wakeup`? The current implemented `EnumSerializableTrait` is based on `Serializable` interface and defined the methods `serialize` and `unserialize`. PHP will ignore `__sleep` / `__wakeup` if an object implements `Serializable`.

Also I have no Idea why you want to clone an enumerator. This is (and should) not be possible by design.

**Comment by Michal-sk** [comment]
You are correct, __clone was wrong to mention.

Strange, i now see what you mean regarding Serializable. I'm using doctrine with caching and got some issues regarding __wakup being called even tough i was implementing Serializable. Will digg in some deeper. Thanks for your support!
