### ISSUE TITLE
Allow usage of own exception class instead of InvalidArgumentException

### ISSUE THREAD

**Issue by sandrokeil** [marc-mabe/php-enum#56]
It would be great if Enums can define an own exception class, which is used instead of `InvalidArgumentException` to work well with an [assertion library](https://github.com/beberlei/assert#your-own-assertion-class "Own exception class example").

What do you think?

**Comment by marc-mabe** [comment]
I don't think I got your point completely. Assertion libraries are great but this enumeration library is more low level in my opinion as it only comes with a workaround for a missing feature of PHP itself and I like to keep is as such. (I don't think that it is/would be possible to change the exception class of any language based feature)

For your example with the nice [assertion library](https://github.com/beberlei/assert#your-own-assertion-class) I would recommend to write your own assertion class that fits exactly your needs.

Something like this (not tested):
```php
namespace MyProject;

use Assert\Assertion;

class EnumAssertion extends Assertion
{
    const INVALID_ENUMERATOR;

    protected static $exceptionClass = 'MyProject\AssertionFailedException';

    public static function isEnum($enumerator, $enumeration, $message = null, $propertyPath = null)
    {
        static::subclassOf($enumeration, 'MabeEnum\Enum', $message, $propertyPath);

        if (!$enumeration::has($enumerator)) {
            $message = ?: sprintf(
                '"%s" is not a valid enumerator of "%s".',
                self::stringify($enumerator),
                self::stringify($enumeration)
            );
            throw static::createException($value, $message, static::INVALID_ENUMERATOR, $propertyPath, array('enumeration' => $enumeration));
        }
    }
}
```

**Comment by sandrokeil** [comment]
I have some value objects and if the value of the enum comes from a string and is wrong, no assertion exception is raised. I will write an own assertion for that. Thanks. :+1:

**Comment by prolic** [comment]
@sandrokeil 

I use something like this:

    Assertion::keyExists($payload, 'language', 'language missing');
    Assertion::true(defined(Language::class . '::' . $payload['language']));
