### ISSUE TITLE
How to return the Enum instance

### ISSUE THREAD

**Issue by eavilesmejia** [marc-mabe/php-enum#85]
Having the class:

```
class ActionType extends Enum
{
    const FOO = 'foo';
    const BAR = 'bar';
}
```
How to get the class instance when we pass an undefined value ?

```
$enumClass = ActionType::class;
$value = 'not_defined_value'

try {
   $enumObject = $enumClass::byValue($value);
} catch( InvalidArgumentException $e) {
  // how to get the ActionType instance ???
  $enumObject = new $enumClass(); 
}
```

**Comment by marc-mabe** [comment]
@eavilesmejia What is *the* enum instance?
An enum instance is one of the defined enumerators. So you have to specify which one you wanna have or implement logic to use a default one.

**Comment by eavilesmejia** [comment]
@marc-mabe I would like to get `ActionType` instance when an `InvalidArgumentException ` exception is throwed

```
try {
   $enumObject = ActionType::byValue($value);
} catch( InvalidArgumentException $e) {
  // how to get the ActionType instance ???
  $enumObject = new ActionType(); 
}
```
Is it currently possible?

**Comment by eavilesmejia** [comment]
@marc-mabe thanks, I think is good enough implement a default one.
