### ISSUE TITLE
Add description to assert()

### ISSUE THREAD

**Issue by tdtm** [marc-mabe/php-enum#95]
Assert has no description at `vendor/marc-mabe/php-enum/src/Enum.php:368` on `assert(self::noAmbiguousValues($publicConstants));`

Should it fail, adding a description would clearly tell what's the issue without having to dig in the source.

I can look at doing a PR for it.

**Comment by marc-mabe** [comment]
fine by me - PR would be nice

**Comment by elenaHristova** [comment]
Hi there,
I ran across the same issue when using byValue(). It seems like it doesn't work at all.

> In Enum.php line 368:
>   Warning: assert(): assert(self::noAmbiguousValues($publicConstants)) failed
